openapi: 3.0.0
info:
 title: User Management API
 description: API для управления пользователями
 version: 1.0.0
tags:
 - name: Users
   description: Управление пользователями
paths:
 /users:
  get:
   summary: Получить всех пользователей
   tags:
    - Users
   responses:
    '200':
     description: Успешно получены все пользователи
     content:
      application/json:
       schema:
        type: array
        items:
         type: object
         properties:
          id:
           type: integer
          username:
           type: string
          email:
           type: string
    '404':
     description: Пользователи не найдены
  post:
   summary: Создать нового пользователя
   tags:
    - Users
   requestBody:
    required: true
    content:
     application/json:
      schema:
       type: object
       properties:
        username:
         type: string
         example: johndoe
        email:
         type: string
         example: johndoe@example.com
        password:
         type: string
         example: password123
   responses:
    '201':
     description: Успешно создан пользователь
     content:
      application/json:
       schema:
        type: object
        properties:
         id:
          type: integer
         username:
          type: string
         email:
          type: string
    '400':
     description: Неверные данные пользователя
 /users/{id}:
  get:
   summary: Получить пользователя по ID
   tags:
    - Users
   parameters:
    - name: id
      in: path
      description: ID пользователя
      required: true
      schema:
       type: integer
   responses:
    '200':
     description: Успешно получен пользователь
     content:
      application/json:
       schema:
        type: object
        properties:
         id:
          type: integer
         username:
          type: string
         email:
          type: string
    '404':
     description: Пользователь не найден
  put:
   summary: Обновить данные пользователя
   tags:
    - Users
   parameters:
    - name: id
      in: path
      description: ID пользователя
      required: true
      schema:
       type: integer
   requestBody:
    required: true
    content:
     application/json:
      schema:
       type: object
       properties:
        username:
         type: string
        email:
         type: string
        password:
         type: string
   responses:
    '200':
     description: Успешно обновлены данные пользователя
     content:
      application/json:
       schema:
