openapi: 3.0.0
info:
  title: FINANCE EXPRESS TS
  version: "1.0.0"
  description: API веб приложение FINANCE EXPRESS для реализации и постпуление услуг и товаров
paths:
  # Подключаем эндпоинты для пользователей
  /users:
    $ref: './users/users.yaml'
servers:
  - url: http://localhost:3000/api